"""add activity fields

Revision ID: 980a207ecda8
Revises: 0e3c84e6e2cb
Create Date: 2026-02-22 21:54:49.207792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '980a207ecda8'
down_revision: Union[str, Sequence[str], None] = '0e3c84e6e2cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_activities', sa.Column('type', sa.String(length=50), nullable=True))
    op.add_column('core_activities', sa.Column('start_date_local', sa.String(length=50), nullable=True))
    op.add_column('core_activities', sa.Column('moving_time', sa.Integer(), nullable=True))
    op.add_column('core_activities', sa.Column('elapsed_time', sa.Integer(), nullable=True))
    op.add_column('core_activities', sa.Column('total_elevation_gain', sa.Float(), nullable=True))
    op.add_column('core_activities', sa.Column('average_speed', sa.Float(), nullable=True))
    op.add_column('core_activities', sa.Column('max_speed', sa.Float(), nullable=True))
    op.add_column('core_activities', sa.Column('average_heartrate', sa.Float(), nullable=True))
    op.add_column('core_activities', sa.Column('max_heartrate', sa.Float(), nullable=True))
    op.add_column('core_activities', sa.Column('average_watts', sa.Float(), nullable=True))
    op.add_column('core_activities', sa.Column('kilojoules', sa.Float(), nullable=True))
    op.add_column('core_activities', sa.Column('calories', sa.Float(), nullable=True))
    op.add_column('core_activities', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('core_activities', sa.Column('gear_id', sa.String(length=50), nullable=True))
    op.add_column('core_activities', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('core_activities_strava_id_key'), 'core_activities', type_='unique')
    op.create_index(op.f('ix_core_activities_strava_id'), 'core_activities', ['strava_id'], unique=True)
    op.drop_column('core_activities', 'elevation')
    op.drop_column('core_activities', 'duration')
    op.drop_column('core_activities', 'avg_power')
    op.drop_column('core_activities', 'avg_hr')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_activities', sa.Column('avg_hr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('core_activities', sa.Column('avg_power', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('core_activities', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('core_activities', sa.Column('elevation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_core_activities_strava_id'), table_name='core_activities')
    op.create_unique_constraint(op.f('core_activities_strava_id_key'), 'core_activities', ['strava_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('core_activities', 'created_at')
    op.drop_column('core_activities', 'gear_id')
    op.drop_column('core_activities', 'description')
    op.drop_column('core_activities', 'calories')
    op.drop_column('core_activities', 'kilojoules')
    op.drop_column('core_activities', 'average_watts')
    op.drop_column('core_activities', 'max_heartrate')
    op.drop_column('core_activities', 'average_heartrate')
    op.drop_column('core_activities', 'max_speed')
    op.drop_column('core_activities', 'average_speed')
    op.drop_column('core_activities', 'total_elevation_gain')
    op.drop_column('core_activities', 'elapsed_time')
    op.drop_column('core_activities', 'moving_time')
    op.drop_column('core_activities', 'start_date_local')
    op.drop_column('core_activities', 'type')
    # ### end Alembic commands ###
